[gcode_macro bunny_start_print]
gcode:
  M220 S100 # Extrudsion rate 100%
  M221 S100 # Speed 100%
  {% set BED_TEMP = params.BED_TEMP|default(60)|float %}
  {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(215)|float %}
  {% set BED_LEVEL_EXTRUDER_TEMP = params.BED_LEVEL_EXTRUDER_TEMP|default(170)|float %}
  G90 ; use absolute coordinates
  M83 ; use extruder relative mode
  G28 ; home all axis
  ; G29 ; bed mesh leveling

  # Init for priting
  M104 S{EXTRUDER_TEMP} ; set extruder tempeprature for priting
  M140 S{BED_TEMP} ; set bed tempeprature for bed leveling
  G92 E0 ; reset extruder position
  G1 Y0 X119 F2400 ; purge line Y axis position
  G1 Z3 F720 ; purge line Z position
  M109 S{EXTRUDER_TEMP} ; wait for extruder temperature
  M190 S{BED_TEMP} ; wait for bed temperature

  # Purge line
  G1 X100 F1000
  G1 Z0.2 F720
  G1 X90 E3 F900
  G1 X30 E10 F700
  G92 E0 ; reset extruder position

  M221 S94 ; set flow to 94%

[gcode_macro bunny_purge]
gcode:
  M400 ; wait for moves to finish
  G92 E0 ; reset extruder position
  M83 ; use extruder relative mode
  G1 E70 F150 ; 70 mm at 2.5 mm/s

[gcode_macro bunny_unload_filament]
gcode:
  M400 ; wait for moves to finish
  G92 E0 ; reset extruder position
  M83 ; use extruder relative mode
  G1 E-10 F3960 ; 10 mm at 66 mm/s
  G4 P500 ; dwell 500 ms
  G1 E-100 F4800 ; 100 mm at 80 mm/s with 1250 mm/s^2

[gcode_macro PRINT_START]
#   Use PRINT_START for the slicer starting script - please customize for your slicer of choice
gcode:
    G28                            ; home all axes
    G90                            ; absolute positioning    
    G1 Z20 F3000                   ; move nozzle away from bed
   
[gcode_macro PRINT_END]
#   Use PRINT_END for the slicer ending script - please customize for your slicer of choice
gcode:
    M400                           ; wait for buffer to clear
    G92 E0                         ; zero the extruder
    G1 E-4.0 F3600                 ; retract filament
    G91                            ; relative positioning

    #   Get Boundaries
    {% set max_x = printer.configfile.config["stepper_x"]["position_max"]|float %}
    {% set max_y = printer.configfile.config["stepper_y"]["position_max"]|float %}
    {% set max_z = printer.configfile.config["stepper_z"]["position_max"]|float %}

    #   Check end position to determine safe direction to move
    {% if printer.toolhead.position.x < (max_x - 20) %}
        {% set x_safe = 20.0 %}
    {% else %}
        {% set x_safe = -20.0 %}
    {% endif %}

    {% if printer.toolhead.position.y < (max_y - 20) %}
        {% set y_safe = 20.0 %}
    {% else %}
        {% set y_safe = -20.0 %}
    {% endif %}

    {% if printer.toolhead.position.z < (max_z - 2) %}
        {% set z_safe = 2.0 %}
    {% else %}
        {% set z_safe = max_z - printer.toolhead.position.z %}
    {% endif %}

    G0 Z{z_safe} F3600             ; move nozzle up
    G0 X{x_safe} Y{y_safe} F20000  ; move nozzle to remove stringing
    TURN_OFF_HEATERS
    M107                           ; turn off fan
    G90                            ; absolute positioning
    G0 X60 Y{max_y} F3600          ; park nozzle at rear
    
[gcode_macro LOAD_FILAMENT]
gcode:
   M83                            ; set extruder to relative
   G1 E30 F300                    ; load
   G1 E15 F150                    ; prime nozzle with filament
   M82                            ; set extruder to absolute
    
[gcode_macro UNLOAD_FILAMENT]
gcode:
   M83                            ; set extruder to relative
   G1 E10 F300                    ; extrude a little to soften tip
   G1 E-40 F1800                  ; retract some, but not too much or it will jam
   M82                            ; set extruder to absolute
