[mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_30FFD5055653353024651343-if00

[temperature_sensor mainboard]
sensor_type: temperature_mcu

[stepper_x] #0
step_pin: PB13
## Refer to https://docs.vorondesign.com/build/startup/#v0
dir_pin: PB12                                                       # Check motor direction in link above. If inverted, add a ! before PB12
enable_pin: !PB14
rotation_distance: 40
microsteps: 32
full_steps_per_rotation: 200                                        # Set to 400 for 0.9째 degree stepper motor, 200 is for 1.8째 stepper motors
endstop_pin: tmc2209_stepper_x:virtual_endstop 

[tmc2209 stepper_x] #0
uart_pin: PC11
tx_pin: PC10
uart_address: 0
interpolate: False
run_current: 0.5
sense_resistor: 0.110
stealthchop_threshold: 0                                            # Set to 999999 to turn stealthchop on, and 0 to use spreadcycle
diag_pin: ^PC0  													# YOU NEED TO JUMP THIS DIAG PIN ON YOUR BOARD FOR SENSORLESS HOMING TO WORK 
driver_SGTHRS: 110                                                  # this is set to 255 which is the MAX sensitivity for sensorless homing, you will need to tune this later

[stepper_y] #1
step_pin: PB10
## Refer to https://docs.vorondesign.com/build/startup/#v0
dir_pin: PB2                                                        # Check motor direction in link above. If inverted, add a ! before PB2
enable_pin: !PB11
rotation_distance: 40
microsteps: 32
full_steps_per_rotation: 200                                        # Set to 400 for 0.9째 degree stepper motor, 200 is for 1.8째 stepper motors
endstop_pin: tmc2209_stepper_y:virtual_endstop

[tmc2209 stepper_y] #1
uart_pin: PC11
tx_pin: PC10
uart_address: 2
interpolate: False
run_current: 0.5
sense_resistor: 0.110
stealthchop_threshold: 0                                            # Set to 999999 to turn stealthchop on, and 0 to use spreadcycle
diag_pin: ^PC1  													# YOU NEED TO JUMP THIS DIAG PIN ON YOUR BOARD FOR SENSORLESS HOMING TO WORK
driver_SGTHRS: 110                                                  # this is set to 255 which is the MAX sensitivity for sensorless homing, you will need to tune this later

[stepper_z] #3
step_pin: PB0
dir_pin: !PC5                                                       # Remove the ! before PC5 if motor direction is inverted.
enable_pin: !PB1
rotation_distance: 8                                                # For T8x8 integrated lead screw
microsteps: 32
endstop_pin: ^PC2

[tmc2209 stepper_z] #3
uart_pin: PC11
tx_pin: PC10
uart_address: 1
interpolate: False
## For OMC (StepperOnline) 17LS13-0404E-200G 0.4A 
#run_current: 0.2
## For LDO-42STH25-1004CL200E 1.0A
run_current: 0.4
sense_resistor: 0.110
stealthchop_threshold: 0                                            # Set to 999999 to turn stealthchop on, and 0 to use spreadcycle

[heater_bed]
# control: pid
heater_pin: PC9
sensor_type: Generic 3950
sensor_pin: PC3
smooth_time: 3.0
#max_power: 0.6                                                     # Only needed for 100w pads
min_temp: 0
max_temp: 120

[fan_generic filter]
pin: PC6
# max_power: 0.8
# cycle_time: 0.00004
# kick_start_time: 0.1
# off_below: 0.5
